<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Boo.Lang.Parser</AssemblyName>
    <RootNamespace>Boo.Lang.Parser</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Boo.Lang/Boo.Lang.csproj" />
    <ProjectReference Include="../Boo.Lang.Compiler/Boo.Lang.Compiler.csproj" />
  </ItemGroup>

</Project>
