namespace Boo.Lang.Parser;

using System.Linq;
using Antlr4.Runtime;
using Boo.Lang.Resources;

/// <summary>
/// Rewrites a raw parser error into the message boo.g would have produced.
///
/// The 2.7 parser carries an equivalent table in GeneratedErrorPatterns,
/// generated by running the snippets in scripts/error-patterns.boo and
/// recording what the parser failed on. This table was captured the same way
/// from the ANTLR 4 parser, which stops in different rules on different
/// tokens, so the entries are not the same ones.
/// </summary>
internal static class BooErrorPatterns
{
	private sealed class Pattern
	{
		public string Message;
		public string Rule;
		public int Token;
		public int Offending = -1;
		public bool NoViableAlt;

		/// Null where the state of the parens does not matter.
		public bool? UnclosedParen;
	}

	private static readonly Pattern[] Patterns =
	{
		Alt(StringResources.BooParser_BlockMustBeIndented, "compound_stmt", BooLexer.COMMA),
		Alt(StringResources.BooParser_BlockMustBeIndented, "compound_stmt", BooLexer.EOL),
		Alt(StringResources.BooParser_BlockMustBeIndented, "parse_module", BooLexer.CLASS),
		Alt(StringResources.BooParser_BlockMustBeIndented, "parse_module", BooLexer.DEDENT),
		Alt(StringResources.BooParser_BlockMustBeIndented, "parse_module", BooLexer.RETURN),
		Alt(StringResources.BooParser_BlockMustBeIndented, "stmt", BooLexer.DEDENT),
		Mismatch(StringResources.BooParser_BlockMustBeIndented, "begin_block_with_doc", BooLexer.INDENT),
		Mismatch(StringResources.BooParser_BlockMustBeIndented, "begin_with_doc", BooLexer.COLON),
		Mismatch(StringResources.BooParser_BlockMustBeIndented, "begin_with_doc", BooLexer.INDENT),
		Mismatch(StringResources.BooParser_BlockMustBeIndented, "class_definition", BooLexer.COLON),

		Alt(StringResources.BooParser_UnbalancedClosingParen, "parse_module", BooLexer.EOL),
		Alt(StringResources.BooParser_UnbalancedClosingParen, "parse_module", BooLexer.ID, unclosedParen: true),
		Alt(StringResources.BooParser_UnbalancedClosingParen, "stmt", BooLexer.CLASS),
		Alt(StringResources.BooParser_UnbalancedClosingParen, "stmt", BooLexer.COLON),
		Alt(StringResources.BooParser_UnbalancedClosingParen, "stmt", BooLexer.DEF),
		Alt(StringResources.BooParser_UnbalancedClosingParen, "stmt", BooLexer.EOL),
		Alt(StringResources.BooParser_UnbalancedClosingParen, "stmt", BooLexer.RBRACK),
		Mismatch(StringResources.BooParser_UnbalancedClosingParen, "base_types", BooLexer.RPAREN),
		Mismatch(StringResources.BooParser_UnbalancedClosingParen, "stmt", BooLexer.EOL, BooLexer.LPAREN),

		Alt(StringResources.BooParser_UnbalancedOpeningParen, "parse_module", BooLexer.RPAREN),
		Mismatch(StringResources.BooParser_UnbalancedOpeningParen,
			"assignment_or_method_invocation_with_block_stmt", BooLexer.EOL, BooLexer.RPAREN),
		Mismatch(StringResources.BooParser_UnbalancedOpeningParen, "macro_stmt", BooLexer.COLON),
		Mismatch(StringResources.BooParser_UnbalancedOpeningParen, "start", TokenConstants.EOF),
		Mismatch(StringResources.BooParser_UnbalancedOpeningParen, "stmt", BooLexer.EOL, BooLexer.ID),

		Alt(StringResources.BooParser_SeparateExpressionsWithCommas, "stmt", BooLexer.ID),
		Alt(StringResources.BooParser_SeparateExpressionsWithCommas, "parse_module", BooLexer.ID, unclosedParen: false),
		Mismatch(StringResources.BooParser_SeparateExpressionsWithCommas,
			"assignment_or_method_invocation_with_block_stmt", BooLexer.EOL, BooLexer.ID),
	};

	private static Pattern Alt(string message, string rule, int token, bool? unclosedParen = null) =>
		new Pattern { Message = message, Rule = rule, Token = token, NoViableAlt = true, UnclosedParen = unclosedParen };

	private static Pattern Mismatch(string message, string rule, int token) => new Pattern { Message = message, Rule = rule, Token = token, NoViableAlt = false };

	private static Pattern Mismatch(string message, string rule, int token, int offending) => new Pattern { Message = message, Rule = rule, Token = token, Offending = offending, NoViableAlt = false };

	/// <summary>
	/// The friendlier message for this failure, or null to keep the original.
	/// </summary>
	public static string Match(IRecognizer recognizer, IToken offendingSymbol, RecognitionException e)
	{
		var parser = recognizer as Parser;
		if (parser == null || offendingSymbol == null || parser.RuleContext == null)
			return null;

		var index = parser.RuleContext.RuleIndex;
		if (index < 0 || index >= parser.RuleNames.Length)
			return null;

		var rule = parser.RuleNames[index];
		var noViableAlt = e is NoViableAltException;

		// boo.g keys the two kinds differently: a no-viable-alternative on the
		// token the parser stopped at, a mismatch on the token it wanted. ANTLR 4
		// carries the wanted set on the exception, or on the parser itself when
		// it reports a missing token with no exception at all.
		var expected = e != null ? e.GetExpectedTokens() : parser.GetExpectedTokens();

		bool? unclosedParen = null;
		var pattern = Patterns.FirstOrDefault(p =>
			p.Rule == rule
			&& p.NoViableAlt == noViableAlt
			&& (p.Offending < 0 || p.Offending == offendingSymbol.Type)
			&& (p.NoViableAlt
				? p.Token == offendingSymbol.Type
				: expected != null && expected.Contains(p.Token))
			&& (p.UnclosedParen == null
				|| p.UnclosedParen == (unclosedParen ??= HasUnclosedParen(parser))));

		var keyword = KeywordText(parser, offendingSymbol);
		if (keyword != null)
		{
			// The table reads a keyword the parser could not start a statement
			// with as a dangling paren the source never had.
			if (pattern != null && pattern.Message == StringResources.BooParser_UnbalancedOpeningParen)
				return string.Format(StringResources.BooParser_KeywordAsIdentifier, keyword);

			// A keyword where a name belongs, in a rule the table has no entry for.
			if (pattern == null && expected != null && expected.Contains(BooLexer.ID))
				return string.Format(StringResources.BooParser_KeywordAsIdentifier, keyword);
		}

		return pattern == null ? null : pattern.Message;
	}

	/// <summary>
	/// The keyword a token spells, or null where it is not one. Reading the
	/// grammar's literal names keeps this in step with BooLexer.g4; operators
	/// have literal names too, and are told apart by not being all letters.
	/// </summary>
	private static string KeywordText(Parser parser, IToken token)
	{
		var literal = parser.Vocabulary.GetLiteralName(token.Type);
		if (literal == null || literal.Length < 3)
			return null;

		var word = literal.Trim('\'');
		return word.All(char.IsLetter) ? word : null;
	}

	/// <summary>
	/// Whether some opening paren is never closed.
	///
	/// A missing comma and a missing paren stop the parser in the same place: an
	/// identifier in parse_module, no viable alternative, identical expected set.
	/// Only the parens themselves tell the two apart.
	/// </summary>
	private static bool HasUnclosedParen(Parser parser)
	{
		var tokens = parser.InputStream as BufferedTokenStream;
		if (tokens == null)
			return false;

		tokens.Fill();
		var depth = 0;
		for (var i = 0; i < tokens.Size; i++)
		{
			var type = tokens.Get(i).Type;
			if (type == BooLexer.LPAREN)
				depth++;
			else if (type == BooLexer.RPAREN)
				depth--;
		}
		return depth > 0;
	}
}
