//
// DO NOT EDIT THIS FILE!
//
// This file was generated automatically by the
// ast.py script on Sat Jan 17 18:51:35 2004
//
using System;

namespace Boo.Lang.Ast
{
	public enum UnaryOperatorType
	{
		ArithmeticNegate,
		Increment,
		Decrement,
		Not
	}
}