#!/bin/sh
# postinst script for boo
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#        * <postinst> `configure' <most-recently-configured-version>
#        * <old-postinst> `abort-upgrade' <new version>
#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
#          <new-version>
#        * <postinst> `abort-remove'
#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#          <failed-install-package> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package


if [ -x /usr/bin/cli-gacutil ]; then
    GACUTIL="/usr/bin/cli-gacutil"
else
    GACUTIL="/usr/bin/gacutil"
fi


case "$1" in
    configure)
    $GACUTIL -i /usr/lib/boo/Boo.Lang.dll
    $GACUTIL -i /usr/lib/boo/Boo.Lang.CodeDom.dll
    $GACUTIL -i /usr/lib/boo/Boo.Lang.Compiler.dll
    $GACUTIL -i /usr/lib/boo/Boo.Lang.Interpreter.dll
    $GACUTIL -i /usr/lib/boo/Boo.Lang.Parser.dll
    $GACUTIL -i /usr/lib/boo/Boo.Lang.Useful.dll
    $GACUTIL -i /usr/lib/boo/Boo.Lang.Extensions.dll
    $GACUTIL -i /usr/lib/boo/Boo.Lang.PatternMatching.dll
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
