<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>booc</AssemblyName>
    <RootNamespace>booc</RootNamespace>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Boo.Lang/Boo.Lang.csproj" />
    <ProjectReference Include="../Boo.Lang.Compiler/Boo.Lang.Compiler.csproj" />
    <ProjectReference Include="../Boo.Lang.Parser/Boo.Lang.Parser.csproj" />
  </ItemGroup>

</Project>
