//
// DO NOT EDIT THIS FILE!
//
// This file was generated automatically by the
// ast.py script on Fri Jan 09 11:50:32 2004
//
using System;

namespace Boo.Ast
{
	public enum BinaryOperatorType
	{
		Add,
		Subtract,
		Multiply,
		Divide,
		Modulus,
		LessThan,
		GreaterThan,
		Equality,
		Inequality,
		Match,
		Assign,
		InPlaceAdd,
		InPlaceSubtract,
		InPlaceMultiply,
		InPlaceDivide,
		ReferenceEquality,
		TypeTest,
		MembershipTest,
		Or,
		And
	}
}