//
// DO NOT EDIT THIS FILE!
//
// This file was generated automatically by the
// ast.py script on Fri Jan 09 11:50:31 2004
//
using System;

namespace Boo.Ast
{
	public enum TypeMemberModifiers
	{
		None,
		Public = 1,
		Protected = 2,
		Private = 4,
		Internal = 8,
		Static = 16,
		Final = 32,
		Transient = 64
	}
}