//
// DO NOT EDIT THIS FILE!
//
// This file was generated automatically by the
// ast.py script on Sat Jan 03 19:33:01 2004
//
using System;

namespace Boo.Ast
{
	public enum UnaryOperatorType
	{
		ArithmeticNegate,
		Increment,
		Decrement,
		Not
	}
}