<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>booc.Tests</AssemblyName>
    <RootNamespace>BooC.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Boo.Lang/Boo.Lang.csproj" />
    <ProjectReference Include="../../src/Boo.Lang.Compiler/Boo.Lang.Compiler.csproj" />
    <ProjectReference Include="../../src/booc/booc.csproj" />
  </ItemGroup>

</Project>
