#region license
// boo - an extensible programming language for the CLI
// Copyright (C) 2004 Rodrigo B. de Oliveira
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
//
// As a special exception, if you link this library with other files to
// produce an executable, this library does not by itself cause the
// resulting executable to be covered by the GNU General Public License.
// This exception does not however invalidate any other reasons why the
// executable file might be covered by the GNU General Public License.
//
// Contact Information
//
// mailto:rbo@acm.org
#endregion

//
// DO NOT EDIT THIS FILE!
//
// This file was generated automatically by the
// ast.py script on Mon Feb 16 22:56:48 2004
//
using System;

namespace Boo.Lang.Ast.Impl
{
	[Serializable]
	public abstract class IfStatementImpl : Statement
	{
		protected Expression _expression;
		protected Block _trueBlock;
		protected Block _falseBlock;
		
		protected IfStatementImpl()
		{
 		}
		
		protected IfStatementImpl(Expression expression, Block trueBlock, Block falseBlock)
		{
 			Expression = expression;
			TrueBlock = trueBlock;
			FalseBlock = falseBlock;
		}
		
		protected IfStatementImpl(LexicalInfo lexicalInfo, Expression expression, Block trueBlock, Block falseBlock) : base(lexicalInfo)
		{
 			Expression = expression;				
			TrueBlock = trueBlock;				
			FalseBlock = falseBlock;				
		}
		
		protected IfStatementImpl(LexicalInfo lexicalInfo) : base(lexicalInfo)
		{
 		}
		
		public override NodeType NodeType
		{
			get
			{
				return NodeType.IfStatement;
			}
		}
		public Expression Expression
		{
			get
			{
				return _expression;
			}
			
			set
			{
				
				if (_expression != value)
				{
					_expression = value;
					if (null != _expression)
					{
						_expression.InitializeParent(this);
					}
				}
			}
		}
		public Block TrueBlock
		{
			get
			{
				return _trueBlock;
			}
			
			set
			{
				
				if (_trueBlock != value)
				{
					_trueBlock = value;
					if (null != _trueBlock)
					{
						_trueBlock.InitializeParent(this);
					}
				}
			}
		}
		public Block FalseBlock
		{
			get
			{
				return _falseBlock;
			}
			
			set
			{
				
				if (_falseBlock != value)
				{
					_falseBlock = value;
					if (null != _falseBlock)
					{
						_falseBlock.InitializeParent(this);
					}
				}
			}
		}
		new public IfStatement CloneNode()
		{
			return (IfStatement)Clone();
		}
		
		override public object Clone()
		{
			IfStatement clone = (IfStatement)System.Runtime.Serialization.FormatterServices.GetUninitializedObject(GetType());
			clone._lexicalInfo = _lexicalInfo;
			clone._documentation = _documentation;
			clone._properties = (System.Collections.Hashtable)_properties.Clone();
			
			if (null != _expression)
			{
				clone._expression = (Expression)_expression.Clone();
			}
			if (null != _trueBlock)
			{
				clone._trueBlock = (Block)_trueBlock.Clone();
			}
			if (null != _falseBlock)
			{
				clone._falseBlock = (Block)_falseBlock.Clone();
			}
			if (null != _modifier)
			{
				clone._modifier = (StatementModifier)_modifier.Clone();
			}
			
			return clone;
		}
		
		override public bool Replace(Node existing, Node newNode)
		{
			if (base.Replace(existing, newNode))
			{
				return true;
			}
			
			if (_expression == existing)
			{
				this.Expression = (Expression)newNode;
				return true;
			}
			if (_trueBlock == existing)
			{
				this.TrueBlock = (Block)newNode;
				return true;
			}
			if (_falseBlock == existing)
			{
				this.FalseBlock = (Block)newNode;
				return true;
			}
			if (_modifier == existing)
			{
				this.Modifier = (StatementModifier)newNode;
				return true;
			}
			return false;
		}
		
		override public void Switch(IAstTransformer transformer, out Node resultingNode)
		{
			IfStatement thisNode = (IfStatement)this;
			Statement resultingTypedNode = thisNode;
			transformer.OnIfStatement(thisNode, ref resultingTypedNode);
			resultingNode = resultingTypedNode;
		}
	}
}
